runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static/
  secure: always
- url: .*
  script: cloud.wsgi.application
  secure: always

libraries:
- name: django
  version: "1.11"
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : '1'